datasets: 
    wikitext103: en
    chinese_documents: zh
    lawmt: en
    en_wiki: en

models:
    copyisallyouneed: 
        model_name: Copyisallyouneed
        dataset_name: CopyisallyouneedWikitext103V2Dataset
    gpt2:
        model_name: GPT2Baseline
        # dataset_name: GPT2Dataset
        dataset_name: GPT2PPLDataset
    knnlm:
        model_name: KNNLMBaseline
        # dataset_name: KNNLMInferenceDataset
        dataset_name: GPT2PPLDataset


# ========= Global configuration ========== #
# root_dir: /dockerdata/johntianlan/sources/Copyisallyouneed
root_dir: /share/data/speech/yanhong/Copyisallyouneed/copyisallyouneed
# data_root_dir: /dockerdata/johntianlan/sources/Copyisallyouneed/data/wikitext103_1024
# data_root_dir: /apdcephfs/share_916081/johntianlan/copyisallyouneed/data/lawmt_1024
data_root_dir: /share/data/speech/yanhong/Copyisallyouneed/data/en_wiki_1024
version: 2004
# ========= Global configuration ========== #
